### ISSUE TITLE
Latest version 3.0.3 in npm is breaking the CICD pipeline 

### ISSUE THREAD

**Issue by gitSambhal** [codebrick-corp/nestjs-ddtrace#21]
Hi @wokim
Version `3.0.3` is breaking my CI/CD pipeline. I am using Nest v9 but this version expects Nestjs v10.
My package.json contains

    "@nestjs/common": "^9.0.0",
    "nestjs-ddtrace": "^3.0.0",

May be you should increase the major version of this package. Currently in npm the package version is 3.0.3 with Nestjs v10 support and 3.0.2 with v9 support. Better to use 4.0.0 instead of 3.0.3.

<img width="771" alt="image" src="https://github.com/codebrick-corp/nestjs-ddtrace/assets/15196655/70f1aad7-05cf-47a0-ae96-df7b5c404fef">

**Comment by wokim** [comment]
Sorry!
I bumped up 4.0.0 but could not unpublish 3.0.3

**Comment by gitSambhal** [comment]
@wokim Can you create new version 3.0.4 for Nestjs 9 so that the builds are not failed?
