### ISSUE TITLE
Update to nestjs v10

### ISSUE THREAD

**Issue by ajaypatidar7722** [codebrick-corp/nestjs-ddtrace#25]
![image](https://github.com/codebrick-corp/nestjs-ddtrace/assets/71318736/00f1d886-319a-4b7b-a6d9-f0e9be21a592)

I'm using nestjs v10 and installing `nestjs-ddtrace` via npm throws the version incompatibility error (See SS attached).

Can you please switch to nest v10?

**Comment by jkalberer** [comment]
It looks like they upgraded the repo for v10 but never released a new version.

**Comment by rbonestell** [comment]
@wokim Could you provide any insight into the timeline for releasing NestJS v10 support? 🙏

**Comment by wokim** [comment]
@rbonestell  Sorry for the delay. I've updated it.
