### ISSUE TITLE
Mismatch between compiled code and TypeScript code on NPM

### ISSUE THREAD

**Issue by voldern** [codebrick-corp/nestjs-ddtrace#9]
Thank you for a great library. 

It seems like the current version (v3.0.0) has a mismatch between the TypeScript and transpiled code.

`DatadogTraceModule.forRoot` takes two arguments according to the `.ts` file (`controllers`, `providers`), but the `.js` file and type definition in the `lib/` folder takes these arguments: `controllers`, `services`.

**Comment by gitSambhal** [comment]
Any update on this?

**Comment by lucaspeterson22** [comment]
It looks like v3.0.1 removed the TS types entirely.

**Comment by wokim** [comment]
Sorry for late response.

**Comment by gitSambhal** [comment]
What are the correct arguments? #10
